"""empty message

Revision ID: 437126f00e1f
Revises: 0e58be3d3d20
Create Date: 2017-06-05 22:41:37.902189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '437126f00e1f'
down_revision = '0e58be3d3d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=100), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
