"""empty message

Revision ID: af17d85e2a97
Revises: 57625af55faa
Create Date: 2017-05-30 20:11:35.320395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af17d85e2a97'
down_revision = '57625af55faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_client', sa.Column('client_secret', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_client', 'client_secret')
    # ### end Alembic commands ###
